[project]
name = "Pupil_LIMlab"
version = "1.1"
description = "A pupil analysis and inference toolkit"
readme = "README.md"
authors = [{name = "Dammy", email = "a.aonih@ucl.ac.uk"}]
requires-python = ">=3.10"
dependencies = [
    "numpy < 2.0.0", 
    "matplotlib",
    "pandas", 
    "scipy < 1.13", 
    "pyyaml", 
    "tqdm", 
    "XdetectionCore >= 0.1.7.4",
    "pytest",
    "loguru",
    "rich",
    "opencv-python",
    "pyinspect == 0.1.0",
    "cloudpickle",
    "fvcore",
    "omegaconf",
    "pycocotools",
    "python-dotenv",
    "imageio[ffmpeg]",
    "scikit-learn",
    "pyarrow",
]


[tool.pytest.ini_options]
testpaths = ["tests"]
norecursedirs = ["build", "dist", "venv*", ".*"]
pythonpath = ["."]