pdatadir_windows: 'X:\Dammy\mouse_pupillometry\mouse_hf'
pdatadir_linux: '/ceph/akrami/Dammy/mouse_pupillometry/mouse_hf/'
tdatadir_windows: 'H:\data\Dammy'
tdatadir_linux: '/nfs/nhome/live/aonih/data/Dammy'
dirstyle: 'N_D_it'
ceph_dir_linux: '/ceph/akrami'
ceph_dir_windows: 'X:\'
# os: unix

dates2process: []


protocol: 'fam'
animals2process: []
session_topology_path: /ceph/akrami/Dammy/Xdetection_mouse_hf_test/session_topology_ephys_2504.csv
pkl_dir_windows: 'X:\Dammy\mouse_pupillometry\pickles'
pkl_dir_linux: '/ceph/akrami/Dammy/mouse_pupillometry/pickles'
do_zscore: true
bandpass_met: [0.0,0]
han_size: 0
fs: 90.0
pdata_topic: 'pupildata_2d'
use_TTL: true
pklname_suffix: 'ephys_2504_stage3_up'
sess_to_redo: []
ow_flag: true
use_canny_ell: false
use_pupilsense: true
use_dlc: false

exclude_dates:

# altrand_dates:
